function out = MapSelectorGUI_testbed(varargin)

% Define properties and set default values.
prop.filterspec = '*';
prop.refilter = '';
prop.redirs = false;
prop.type = {};
prop.prompt = 'Select files';
prop.numfiles = [];
prop.append = [];
prop.output = 'cell';
filenames = 'test';
file_picks = {};
path_cell = {};

% Get figure position preference and create figure.
% gray = [220 220 220]/255;
if ispref('uipickfiles','figure_position')
	fig_pos = getpref('uipickfiles','figure_position');
	create_fcn = @movegui;
else
	fig_pos = [0 0 740 494];
	create_fcn = {@movegui,'center'};
end
fig = figure('Position',fig_pos,...
	'MenuBar','none',...
	'WindowStyle','modal',...
	'Resize','on',...
	'NumberTitle','off',...
	'Name',prop.prompt,...
	'IntegerHandle','off',...
	'CloseRequestFcn',@cancel,...
	'CreateFcn',create_fcn,...
	'ButtonDownFcn',@reset_figure_size,...
	'KeyPressFcn',@keypressmisc,...
	'Visible','off');
if ~isMATLABReleaseOlderThan("R2025a")
	s = settings;
	fig_theme = string(s.matlab.appearance.CurrentTheme.ActiveValue);
	fig.Theme = fig_theme;
else
	fig_theme = "Light";
end
% pause(1)
% fig_color = fig.Color;

% Set system-dependent items.
if ismac
% 	ver = char(java.lang.System.getProperty('os.version'));
	ppi = get(groot,'ScreenPixelsPerInch');
	set(fig,'DefaultUIControlFontName','Lucida Grande')
	set(fig,'DefaultUIControlFontSize',13*72/ppi)
	sort_ctrl_size = 12*72/ppi;
	mod_key = 'command';
	action = 'Control-click';
elseif ispc
% 	ver = str2double(java.lang.System.getProperty('os.version'));
	% set(fig,'DefaultUIControlFontName','Segoe UI')
	set(fig,'DefaultUIControlFontName','Helvetica')
	set(fig,'DefaultUIControlFontSize',9)
	sort_ctrl_size = 7;
	mod_key = 'control';
	action = 'Right-click';
else
	set(fig,'DefaultUIControlFontName','Dialog')
	sort_ctrl_size = get(fig,'DefaultUIControlFontSize') - 1;
	mod_key = 'control';
	action = 'Right-click';
end

% Create uicontrols.
frame1 = uicontrol(fig,'Style','frame',...
	'Position',[255 260 110 70]);
frame2 = uicontrol(fig,'Style','frame',...
	'Position',[275 135 110 100]);

navlist = uicontrol(fig,'Style','listbox',...
	'Position',[10 10 250 320],...
	'String',filenames,...
	'Value',[],...
	'Callback',@clicknav,...
	'KeyPressFcn',@keypressnav,...
	'Max',2);

tri_up = repmat([1 1 1 1 0 1 1 1 1;1 1 1 0 0 0 1 1 1;1 1 0 0 0 0 0 1 1;...
	1 0 0 0 0 0 0 0 1],[1 1 3]);
tri_up(tri_up == 1) = NaN;
tri_down = tri_up(end:-1:1,:,:);
tri_null = NaN(4,9,3);
tri_icon = {tri_down,tri_null,tri_up};
sort_state = [1 0 0 0];
last_sort_state = [1 1 1 1];
sort_cb = gobjects(1,4);
sort_cb(1) = uicontrol(fig,'Style','checkbox',...
	'Position',[15 331 70 15],...
	'String','Name',...
	'FontSize',sort_ctrl_size,...
	'Value',sort_state(1),...
	'CData',tri_icon{sort_state(1)+2},...
	'KeyPressFcn',@keypressmisc,...
	'Callback',{@sort_type,1});
sort_cb(2) = uicontrol(fig,'Style','checkbox',...
	'Position',[85 331 70 15],...
	'String','Nat',...
	'FontSize',sort_ctrl_size,...
	'Value',sort_state(2),...
	'CData',tri_icon{sort_state(2)+2},...
	'KeyPressFcn',@keypressmisc,...
	'Callback',{@sort_type,2});
if isempty(which('sort_nat'))
	% Disable natural order sort if sort_nat is not available.
	sort_cb(2).Enable = 'off';
end
sort_cb(3) = uicontrol(fig,'Style','checkbox',...
	'Position',[155 331 70 15],...
	'String','Date',...
	'FontSize',sort_ctrl_size,...
	'Value',sort_state(3),...
	'CData',tri_icon{sort_state(3)+2},...
	'KeyPressFcn',@keypressmisc,...
	'Callback',{@sort_type,3});
sort_cb(4) = uicontrol(fig,'Style','checkbox',...
	'Position',[225 331 70 15],...
	'String','Size',...
	'FontSize',sort_ctrl_size,...
	'Value',sort_state(4),...
	'CData',tri_icon{sort_state(4)+2},...
	'KeyPressFcn',@keypressmisc,...
	'Callback',{@sort_type,4});

pickslist = uicontrol(fig,'Style','listbox',...
	'Position',[380 10 350 320],...
	'String',file_picks,...
	'Callback',@clickpicks,...
	'KeyPressFcn',@keypresslist,...
	'Max',2,...
	'Value',[]);

openbut = uicontrol(fig,'Style','pushbutton',...
	'Position',[265 295 90 30],...
	'String','Open',...
	'Enable','off',...
	'KeyPressFcn',@keypressmisc,...
	'Callback',@open);

% arrow = [ ...
% 	'        1   ';
% 	'        10  ';
% 	'         10 ';
% 	'000000000000';
% 	'         10 ';
% 	'        10  ';
% 	'        1   '];
% cmap = NaN(128,3);
% cmap(double('10'),:) = [0.5 0.5 0.5;0 0 0];
% arrow_im = NaN(7,76,3);
% arrow_im(:,45:56,:) = ind2rgb(double(arrow),cmap);
add_cm = uicontextmenu(fig);
add_cm_items(1) = uimenu(add_cm,...
	'Label','Add with path subfolders',...
	'Callback',{@add_with_subfolders,'pathsub'},...
	'Visible','off');
add_cm_items(2) = uimenu(add_cm,...
	'Label','Add with subfolders',...
	'Callback',{@add_with_subfolders,'sub'},...
	'Visible','off');
add_cm_items(3) = uimenu(add_cm,...
	'Label','<html>Add with <i>all</i> subfolders</html>',...
	'Separator','on',...
	'Callback',{@add_with_subfolders,'allsub'},...
	'Visible','off');
addbut = uicontrol(fig,'Style','pushbutton',...
	'Position',[265 265 90 30],...
	'String','Add ➔',...
	'Enable','off',...
	'KeyPressFcn',@keypressmisc,...
	'Callback',@add,...
	'UIContextMenu',add_cm);

removebut = uicontrol(fig,'Style','pushbutton',...
	'Position',[285 200 90 30],...
	'String','Remove',...
	'Enable','off',...
	'KeyPressFcn',@keypressmisc,...
	'Callback',@remove);
moveupbut = uicontrol(fig,'Style','pushbutton',...
	'Position',[285 170 90 30],...
	'String','Move Up',...
	'Enable','off',...
	'KeyPressFcn',@keypressmisc,...
	'Callback',@moveup);
movedownbut = uicontrol(fig,'Style','pushbutton',...
	'Position',[285 140 90 30],...
	'String','Move Down',...
	'Enable','off',...
	'KeyPressFcn',@keypressmisc,...
	'Callback',@movedown);

dir_popup = uicontrol(fig,'Style','popupmenu',...
	'Position',[10 350 225 20],...
	'String',path_cell,...
	'Value',length(path_cell),...
	'KeyPressFcn',@keypressmisc,...
	'Callback',@dirpopup);

uparrow = [ ...
	'  0     ';
	' 000    ';
	'00000   ';
	'  0     ';
	'  0     ';
	'  0     ';
	'  0     ';
	'  0     ';
	'  000000'];
cmap = NaN(128,3);
if fig_theme == "Light"
	cmap(double('0'),:) = [0 0 0];
elseif fig_theme == "Dark"
	cmap(double('0'),:) = [1 1 1];
end
uparrow_im = ind2rgb(double(uparrow),cmap);
up_dir_but = uicontrol(fig,'Style','pushbutton',...
	'Position',[240 350 20 20],...
	'CData',uparrow_im,...
	'KeyPressFcn',@keypressmisc,...
	'Callback',@dir_up_one,...
	'ToolTip','Go to parent folder');
% up_dir_but = uicontrol(fig,'Style','pushbutton',...
% 	'Position',[240 350 20 20],...
% 	'String','⬆',...
% 	'KeyPressFcn',@keypressmisc,...
% 	'Callback',@dir_up_one,...
% 	'ToolTip','Go to parent folder');
if length(path_cell) > 1
	up_dir_but.Enable = 'on';
else
	up_dir_but.Enable = 'off';
end

hist_cm = uicontextmenu(fig);

% If necessary, add warning about number of items to be selected.
% num_files_warn = uicontrol(fig,'Style','text',...
% 	'Position',[380 385 350 16],...
% 	'String',numstr,...
% 	'ForegroundColor',[0.8 0 0],...
% 	'HorizontalAlignment','center',...
% 	'Visible','off');
% if ~isempty(prop.numfiles)
% 	num_files_warn.Visible = 'on';
% end
%resize()

cancel_button = uicontrol(fig,'Style','pushbutton',...
	'Position',[280 30 80 30],...
	'String','Cancel',...
	'KeyPressFcn',@keypressmisc,...
	'Callback',@cancel);

% Make figure visible and hide handle.
set(fig,'HandleVisibility','off',...
	'Visible','on',...
	'ResizeFcn',@resize)

% Wait until figure is closed.
uiwait(fig)

% Compute desired output.
switch prop.output
	case 'cancel'
		out = 0;
end

end

function cancel(varargin)
		prop.output = 'cancel';
		%fig_pos = fig.Position;
		delete(fig)
	end

function CloseRequestFcn(fig)
    delete(fig);
end

function MapSelectorGUI_testbed_CloseRequestFcn(hObject, eventdata, handles)
    % Add your custom cleanup code here (e.g., save data, clear variables)
    disp('GUI is closing...');

    % This line is essential to actually close the figure
    delete(hObject); 
end
